# Theme Settings
remote_theme             : "mmistakes/minimal-mistakes@4.17.2"
minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "en-US"
title                    : "Marcello Roy"
title_separator          : "-"
name                     : "Marcello Roy"
description              : "Portfolio Marcello Roy"
logo                     : "/assets/images/logo-707x200.png"
masthead_title           : " "
breadcrumbs              : true
words_per_minute         : 160

# Comments (optional)
comments:
  provider               : false

# SEO Related
google_site_verification : "v4DTrYOO1JCGDyFYkTQANpSTh5i19K2Fqjm5DurJj9w"

# Social Sharing
og_image                 : "https://images.unsplash.com/photo-1484417894907-623942c8ee29?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80"

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "Marcello Roy"
  avatar           : "/assets/images/roy-profile.png"
  bio              : "<i>AI Practicioner,<br>Technology Enthusiast,<br> dan Learner.</i>"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:marcello2k18@gmail.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marcello2k18"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marcelloroy/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/-"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/-"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/usernamekamu
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/usernamekamu/
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/usernamekamu"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: https://www.youtube.com/channel/channelkamu

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
timezone: Asia/Jakarta

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Compress HTML
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  resources:
    output: true
    permalink: /:collection/:path/

collections:
  pages:
    output: true
    permalink: /:tittle/

# Defaults
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: resources
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
